name: PR Pipeline

on: 
    pull_request:
            branches: [main]
            types:
                - opened
                - synchronize   
        
jobs: 
    build-and-test:
        uses: ./.github/workflows/reusable-build-test.yml 
        with:
            run_tests: true
            go_version: "1.22"

    pr-comment:
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - name: Print PR Summary
              run: |
                echo "Branch:${{ github.head_ref}}"
                echo "Test Result: ${{ needs.build-and-test.outputs.test_result }}"

