name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string

      run_tests:
        required: false
        default: true
        type: boolean

    outputs:
      test_result:
        description: Test execution result
        value: ${{ jobs.build-and-test.outputs.job_test_result }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      job_test_result: ${{ steps.set-test-result.outputs.test_result }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        id: run-tests
        if: ${{ inputs.run_tests }}
        continue-on-error: true
        run: go test ./...

      - name: Set Test Result
        id: set-test-result
        run: |
          if [ "${{ steps.run-tests.outcome }}" = "success" ]; then
            echo "test_result=passed" >> $GITHUB_OUTPUT
          else
            echo "test_result=failed" >> $GITHUB_OUTPUT
          fi
